name: Level 1 - Deploy Blog Preview Card

on:
  push:
    branches:
      - main
    paths:
      - '1-newbie-level/blog-preview-card/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: QR Code Component
    uses: ./.github/workflows/github-action-and-gh-page.yml
    with:
      workflow-name: Level 1 - Deploy QR Code Component
      working-dir: 1-newbie-level/blog-preview-card
    secrets:
      DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
