name: Level 1 - Deploy QR Code Component

on:
  push:
    branches:
      - main
    paths:
      - '1-newbie-level/qr-code-component/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: QR Code Component
    uses: ./.github/workflows/github-action-and-gh-page.yml
    with:
      workflow-name: Level 1 - QR Code Component
      working-dir: 1-newbie-level/qr-code-component
    secrets:
      DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
