name: Reusable Github Actions Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      workflow-name:
        description: 'The name of the workflow'
        required: true
        type: string
      working-dir:
        description: 'The local working directory of the project to build'
        required: true
        type: string
      node-version:
        description: 'The Node.js version to use'
        required: false
        default: '24'
        type: string
    secrets:
      DEPLOY_TOKEN:
        description: 'GitHub token for authentication'
        required: true

permissions:
  contents: write

jobs:
  build-project:
    name: Build the project
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Calculate Safe Artifact Name
        id: conver-safe-name
        run: |
          SAFE_DIR_NAME=$(echo '${{ inputs.working-dir }}' | tr / -)

          echo "artifact_name=deploy-artifacts-$SAFE_DIR_NAME" >> $GITHUB_OUTPUT

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.conver-safe-name.outputs.artifact_name }}
          path: ${{ inputs.working-dir }}/dist
          retention-days: 1

    outputs:
      artifact_name: ${{ steps.conver-safe-name.outputs.artifact_name }}

  deploy-to-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-project.outputs.artifact_name }}
          path: ./artifact

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./artifact
          destination_dir: ${{ inputs.working-dir }}
          publish_branch: gh-pages
